/** Approved manifest only. No reclassification, file updates, or direct File creation. */
import 'dotenv/config';
import { createHash } from 'node:crypto';
import { readFile, writeFile, rename, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import { Client } from 'pg';
import { v2 as cloudinary } from 'cloudinary';
import { S3Client, ListObjectsV2Command } from '@aws-sdk/client-s3';
import { db } from '../../lib/db';
import { normalizeDatabaseUrl } from '../../lib/db/connection-string';
import { createUploadedFile } from '../../lib/files/create-uploaded-file';
import { createSectionGroup, createSection } from '../../lib/structure/mutations';
import { createFolder, listFolderOverviews } from '../../lib/structure/folders';
import { resolveStorageProvider } from '../../lib/storage/provider';
import { validateFile } from '../../lib/validation/file';
import { readObject } from '../../lib/storage';
import { formatPersonName } from '../../lib/users/display-name';
import { buildProjectBreadcrumb } from '../../lib/structure/breadcrumb';
import { resolveUploadContext } from '../../lib/structure/upload-context';
import { AuditActions } from '../../lib/admin/audit';

type Entry = {relativePath:string;filename:string;extension:string;sizeBytes:number;sha256:string;status:string;targetProject:string;targetPart:string;partId:string|null;targetGroup:string;targetSection:string;nestedFolder:string|null;detectedKind:string;expectedStorageProvider:string;duplicateOf:string|null};
type Result = {relativePath:string;identity:string;status:string;fileId?:string;sizeBytes:number;provider?:string;error?:string};
const REPORT='reports/import/new-safi-batch-live-report.json', JOURNAL='reports/import/new-safi-batch-live-journal.json', BASELINE='reports/import/new-safi-batch-live-baseline.json';
const root=path.resolve('source_import/new_safi_batch');
const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
const identity=(e:Entry)=>JSON.stringify([e.sha256,e.targetProject,e.partId,e.targetGroup,e.targetSection,e.nestedFolder]);
async function json(p:string){try{return JSON.parse(await readFile(p,'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return null;throw e;}}
async function save(p:string,v:unknown){await writeFile(p+'.tmp',JSON.stringify(v,null,2)+'\n');await rename(p+'.tmp',p);}
async function walk(p:string):Promise<string[]>{const out:string[]=[];for(const e of await readdir(p,{withFileTypes:true})){const f=path.join(p,e.name);if(e.isDirectory())out.push(...await walk(f));else if(e.isFile())out.push(path.relative(root,f).replaceAll('\\','/'));}return out;}
async function storageInventory(){
 cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET,secure:true});
 const cloudKeys:string[]=[];for(const resource_type of ['image','video','raw'] as const){let cursor:string|undefined;do{const r=await cloudinary.api.resources({resource_type,type:'authenticated',max_results:500,next_cursor:cursor});for(const x of r.resources??[])cloudKeys.push(`${resource_type}:${x.public_id}`);cursor=r.next_cursor;}while(cursor);}
 const s3=new S3Client({endpoint:process.env.B2_ENDPOINT,region:process.env.B2_REGION,credentials:{accessKeyId:process.env.B2_KEY_ID!,secretAccessKey:process.env.B2_APPLICATION_KEY!},requestChecksumCalculation:'WHEN_REQUIRED',responseChecksumValidation:'WHEN_REQUIRED'});const b2Keys:string[]=[];let token:string|undefined;do{const r=await s3.send(new ListObjectsV2Command({Bucket:process.env.B2_BUCKET_NAME,ContinuationToken:token}));for(const x of r.Contents??[])if(x.Key)b2Keys.push(x.Key);token=r.IsTruncated?r.NextContinuationToken:undefined;}while(token);s3.destroy();return {cloudinary:cloudKeys.sort(),b2:b2Keys.sort()};
}
async function main(){
 await mkdir('reports/import',{recursive:true});
 const manifest=await json('reports/import/new-safi-batch-manifest.json');const entries:Entry[]=manifest.files;
 const discovered=(await walk(root)).sort();if(JSON.stringify(discovered)!==JSON.stringify(entries.map(e=>e.relativePath).sort()))throw Error('Source inventory differs from approved manifest.');
 if(entries.length!==154||entries.filter(e=>e.status==='READY').length!==153)throw Error('Approved counts differ.');
 const actor=await db.user.findUnique({where:{email:'naciri@archeritage.ma'}});if(!actor||actor.status!=='ACTIVE')throw Error('Uploader missing/inactive.');
 const territory=await db.territoire.findFirst({where:{name:'Safi Patrimoine'}});if(!territory)throw Error('Territory missing.');
 const projects=await db.project.findMany({where:{territoireId:territory.id,isActive:true}});
 const ready=entries.filter(e=>e.status==='READY');for(const e of ready){if(!projects.some(p=>p.name===e.targetProject)||e.partId!==null||e.targetPart!=='GLOBAL')throw Error('Unexpected approved project/part.');}
 // A session advisory lock serializes concurrent runs of this importer without holding a DB transaction across uploads.
 const lock=new Client({connectionString:normalizeDatabaseUrl(process.env.DATABASE_URL),connectionTimeoutMillis:15000});await lock.connect();
 const locked=await lock.query('SELECT pg_try_advisory_lock(9242026, 105) AS locked');if(!locked.rows[0].locked){await lock.end();throw Error('Another new SAFI importer is running.');}
 try{
 let baseline=await json(BASELINE);if(!baseline){const files=await db.file.findMany({orderBy:{id:'asc'}});if(files.length!==753)throw Error(`Expected 753 existing rows, found ${files.length}.`);baseline={files,storage:await storageInventory(),projects:await db.project.findMany(),parts:await db.part.findMany()};await save(BASELINE,baseline);}
 const journal:Record<string,{fileId:string;sha256:string;sectionId:string;folderId:string|null;storageKey:string;provider:string;sizeBytes:number}>=await json(JOURNAL)??{};
 const structure:Record<string,string>={};const destinations=new Map<string,{sectionId:string;folderId:string|null;projectId:string}>();
 async function mutation<T>(create:()=>Promise<T>,reload:()=>Promise<T|null>):Promise<T>{try{return await create();}catch(e){if(!(e instanceof Error)||!/static generation store|incremental cache|request store/i.test(e.message))throw e;const row=await reload();if(!row)throw e;return row;}}
 async function destination(e:Entry){const key=JSON.stringify([e.targetProject,e.partId,e.targetGroup,e.targetSection,e.nestedFolder]);const cached=destinations.get(key);if(cached)return cached;const project=projects.find(p=>p.name===e.targetProject)!;
 const gw={projectId:project.id,partId:e.partId,name:e.targetGroup};let group=await db.sectionGroup.findFirst({where:gw});if(!group){group=await mutation(()=>createSectionGroup(gw,actor!.id),()=>db.sectionGroup.findFirst({where:gw}));structure[`group:${group.id}`]='created';}else structure[`group:${group.id}`]??='reused';
 const sw={groupId:group.id,name:e.targetSection};let section=await db.section.findFirst({where:sw});if(!section){section=await mutation(()=>createSection(sw,actor!.id),()=>db.section.findFirst({where:sw}));structure[`section:${section.id}`]='created';}else structure[`section:${section.id}`]??='reused';if(!section.isActive)throw Error('Destination section inactive.');
 let folderId:string|null=null;if(e.nestedFolder){const fw={sectionId:section.id,parentId:null,name:e.nestedFolder};let folder=await db.folder.findFirst({where:fw});if(!folder){folder=await createFolder(fw,actor!.id);structure[`folder:${folder.id}`]='created';}else structure[`folder:${folder.id}`]??='reused';folderId=folder.id;}
 const target={sectionId:section.id,folderId,projectId:project.id};destinations.set(key,target);return target;}
 async function pass(label:string){const results:Result[]=[];for(const e of ready){const id=identity(e);try{
 const absolute=path.resolve(root,e.relativePath);if(!absolute.startsWith(root+path.sep))throw Error('Invalid source path.');let bytes:Buffer;try{bytes=await readFile(absolute);}catch{results.push({relativePath:e.relativePath,identity:id,status:'SOURCE_CHANGED',sizeBytes:e.sizeBytes});continue;}if(bytes.length!==e.sizeBytes||sha(bytes)!==e.sha256){results.push({relativePath:e.relativePath,identity:id,status:'SOURCE_CHANGED',sizeBytes:e.sizeBytes});continue;}
 const metadata=validateFile(e.filename,'',bytes.subarray(0,64),bytes.length);if(resolveStorageProvider({filename:e.filename,extension:e.extension,sizeBytes:e.sizeBytes})!==e.expectedStorageProvider)throw Error('Provider decision differs from approved manifest.');
 const target=await destination(e);const saved=journal[id];let existing=saved?await db.file.findUnique({where:{id:saved.fileId}}):null;
 if(existing&&(existing.sectionId!==target.sectionId||existing.folderId!==target.folderId||existing.storageKey!==saved.storageKey||existing.size!==e.sizeBytes))throw Error('Journal record differs from actual destination.');
 if(!existing){const candidates=await db.file.findMany({where:{sectionId:target.sectionId,folderId:target.folderId,size:e.sizeBytes}});for(const candidate of candidates){const remote=await readObject(candidate,false,null,true);const b=Buffer.from(await new Response(remote.body).arrayBuffer());if(sha(b)===e.sha256){existing=candidate;break;}}}
 if(existing){journal[id]={fileId:existing.id,sha256:e.sha256,sectionId:target.sectionId,folderId:target.folderId,storageKey:existing.storageKey,provider:existing.storageProvider,sizeBytes:e.sizeBytes};await save(JOURNAL,journal);results.push({relativePath:e.relativePath,identity:id,status:'ALREADY_IMPORTED',fileId:existing.id,sizeBytes:e.sizeBytes,provider:existing.storageProvider});}
 else{const record=await createUploadedFile({userId:actor!.id,projectId:target.projectId,partId:e.partId,sectionId:target.sectionId,folderId:target.folderId,originalName:e.filename,mimeType:metadata.mimeType,sizeBytes:bytes.length,source:bytes});journal[id]={fileId:record.id,sha256:e.sha256,sectionId:target.sectionId,folderId:target.folderId,storageKey:record.storageKey,provider:record.storageProvider,sizeBytes:e.sizeBytes};await save(JOURNAL,journal);results.push({relativePath:e.relativePath,identity:id,status:'UPLOADED',fileId:record.id,sizeBytes:e.sizeBytes,provider:record.storageProvider});}
 }catch(error){results.push({relativePath:e.relativePath,identity:id,status:'FAILED',sizeBytes:e.sizeBytes,error:error instanceof Error?error.message:String(error)});}
 await save('.cache/new-safi-live-progress.json',{label,results});if(results.length%25===0||results.length===ready.length)console.log(`[new-safi-import] ${label} ${results.length}/${ready.length} complete; uploaded=${results.filter(r=>r.status==='UPLOADED').length} already=${results.filter(r=>r.status==='ALREADY_IMPORTED').length} failed=${results.filter(r=>r.status==='FAILED').length}`);
 }return results;}
 const firstPass=await pass('first pass');const afterFirst=await storageInventory();const firstDb=await db.file.count();const firstStructure={groups:await db.sectionGroup.count(),sections:await db.section.count(),folders:await db.folder.count()};
 const secondPass=await pass('retry');const afterRetry=await storageInventory();const finalFiles=await db.file.findMany({orderBy:{id:'asc'}});const finalById=new Map(finalFiles.map(f=>[f.id,f]));const oldChanged=baseline.files.filter((f:{id:string})=>JSON.stringify(finalById.get(f.id))!==JSON.stringify(f)).map((f:{id:string})=>f.id);
 const imported=ready.filter(e=>journal[identity(e)]).map(e=>({entry:e,record:finalById.get(journal[identity(e)].fileId)!}));
 const checks={existing753Untouched:oldChanged.length===0,changedExistingIds:oldChanged,finalDbCount:finalFiles.length,expected906:finalFiles.length===906,projectsUnchanged:JSON.stringify(await db.project.findMany())===JSON.stringify(baseline.projects),partsUnchanged:JSON.stringify(await db.part.findMany())===JSON.stringify(baseline.parts),retryDbUnchanged:finalFiles.length===firstDb,retryStorageUnchanged:JSON.stringify(afterFirst)===JSON.stringify(afterRetry),retryStructureUnchanged:JSON.stringify(firstStructure)===JSON.stringify({groups:await db.sectionGroup.count(),sections:await db.section.count(),folders:await db.folder.count()}),oldStorageObjectsRetained:baseline.storage.cloudinary.every((k:string)=>afterRetry.cloudinary.includes(k))&&baseline.storage.b2.every((k:string)=>afterRetry.b2.includes(k)),mappingErrors:[] as string[],auditMissing:[] as string[],folderOverviews:[] as Awaited<ReturnType<typeof listFolderOverviews>>,breadcrumbs:[] as ReturnType<typeof buildProjectBreadcrumb>[],downloadChecks:[] as Record<string,unknown>[]};
 for(const {entry:e,record:r} of imported){const context=await resolveUploadContext({sectionId:r.sectionId,folderId:r.folderId});if(context.projectId!==projects.find(p=>p.name===e.targetProject)!.id||context.partId!==e.partId||r.uploadedById!==actor.id||r.storageProvider!==e.expectedStorageProvider||r.size!==e.sizeBytes)checks.mappingErrors.push(r.id);const audit=await db.auditLog.findFirst({where:{entityType:'File',entityId:r.id,action:AuditActions.DOCUMENT_UPLOADED,actorUserId:actor.id}});if(!audit)checks.auditMissing.push(r.id);}
 for(const target of destinations.values()){const section=await db.section.findUnique({where:{id:target.sectionId},include:{group:{include:{project:true}}}});if(!section)continue;checks.breadcrumbs.push(buildProjectBreadcrumb({territoire:territory,project:section.group.project,group:section.group,section,folders:target.folderId?[await db.folder.findUniqueOrThrow({where:{id:target.folderId}})]:[]}));if(target.folderId)checks.folderOverviews.push(...await listFolderOverviews(target.sectionId,null));}
 // Sample actual storage download paths for every file kind, without opening image/video content.
 for(const ext of ['pdf','docx','jpeg','mp4']){const sample=imported.find(x=>x.entry.extension===ext);if(!sample)continue;try{const result=await readObject(sample.record,false,null,true);const bytes=Buffer.from(await new Response(result.body).arrayBuffer());checks.downloadChecks.push({extension:ext,fileId:sample.record.id,status:result.status,bytes:bytes.length,sha256Matches:sha(bytes)===sample.entry.sha256});}catch(error){checks.downloadChecks.push({extension:ext,error:error instanceof Error?error.message:String(error)});}}
 const count=(p:(x:typeof imported[number])=>boolean)=>imported.filter(p).length;const associated=Object.fromEntries([...new Set(imported.filter(x=>x.entry.targetSection==='Monuments & ouvrages associés').map(x=>x.entry.nestedFolder!))].map(n=>[n,count(x=>x.entry.targetSection==='Monuments & ouvrages associés'&&x.entry.nestedFolder===n)]));
 const totals={discovered:discovered.length,ready:ready.length,uploadedFirstPass:firstPass.filter(r=>r.status==='UPLOADED').length,alreadyImported:firstPass.filter(r=>r.status==='ALREADY_IMPORTED').length,skippedDuplicates:entries.filter(e=>e.status==='DUPLICATE').length,sourceChanged:firstPass.filter(r=>r.status==='SOURCE_CHANGED').length,failed:firstPass.filter(r=>r.status==='FAILED').length,chateau:count(x=>x.entry.targetProject==='Château de Mer'),muraillesGlobal:count(x=>x.entry.targetProject==='Murailles portugaises de Safi'),historicalPhotos:count(x=>x.entry.nestedFolder==='Photographies historiques'),currentPhotos:count(x=>x.entry.nestedFolder==='Photographies actuelles'),videos:count(x=>x.entry.detectedKind==='video'),cloudinaryUploads:firstPass.filter(r=>r.status==='UPLOADED'&&r.provider==='CLOUDINARY').length,b2Uploads:firstPass.filter(r=>r.status==='UPLOADED'&&r.provider==='BACKBLAZE_B2').length,bytesUploaded:firstPass.filter(r=>r.status==='UPLOADED').reduce((a,r)=>a+r.sizeBytes,0),finalDbFileCount:finalFiles.length};
 const report={generatedAt:new Date().toISOString(),manifestSha256:sha(await readFile('reports/import/new-safi-batch-manifest.json')),uploader:{email:actor.email,displayName:formatPersonName(actor),id:actor.id},totals,associatedMonuments:associated,skipped:entries.filter(e=>e.status!=='READY').map(e=>({relativePath:e.relativePath,status:e.status,duplicateOf:e.duplicateOf})),structure,firstPass,secondPass,retry:{uploaded:secondPass.filter(r=>r.status==='UPLOADED').length,alreadyImported:secondPass.filter(r=>r.status==='ALREADY_IMPORTED').length,failed:secondPass.filter(r=>r.status==='FAILED').length,dbUnchanged:checks.retryDbUnchanged,storageUnchanged:checks.retryStorageUnchanged,structureUnchanged:checks.retryStructureUnchanged},storageCounts:{before:{cloudinary:baseline.storage.cloudinary.length,b2:baseline.storage.b2.length},afterFirst:{cloudinary:afterFirst.cloudinary.length,b2:afterFirst.b2.length},afterRetry:{cloudinary:afterRetry.cloudinary.length,b2:afterRetry.b2.length}},validation:checks};await save(REPORT,report);await writeFile('reports/import/new-safi-batch-live-summary.txt',JSON.stringify({totals,associatedMonuments:associated,retry:report.retry,existing753Untouched:checks.existing753Untouched,validation:checks},null,2)+'\n');console.log(JSON.stringify({totals,retry:report.retry,oldChanged:oldChanged.length,auditMissing:checks.auditMissing.length},null,2));
 }finally{await lock.query('SELECT pg_advisory_unlock(9242026, 105)');await lock.end();}
}
main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1;}).finally(()=>db.$disconnect());


